version: "3.8"

services:
  db:
    image: postgres:18
    restart: always
    command: postgres -c 'max_connections=200' -c 'shared_buffers=24MB'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mvpdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mvpdb?schema=public
      JWT_SECRET: 784c03805b35add1859289e544b5304d02e403a5d904efeb672561d2f9af715b2e9b233224a9161169f348e9833c320c470e2d22f099f3f0b289c7f0b35751ac
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3001:3000"

volumes:
  postgres_data:
  pgadmin_data:
